// backend/models/Image.js
const mongoose = require('mongoose');

const ImageSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
  },
  description: {
    type: String,
    trim: true,
  },
  // Stores the relative path/URL to the file on the server
  imageUrl: {
    type: String, 
    required: true,
  },
  // Stores the actual filename generated by multer (useful for deletion)
  originalName: {
    type: String, 
    required: true,
  },
}, { timestamps: true });

module.exports = mongoose.model('Image', ImageSchema);